version: '3'
services:
  backend:
    image: leechanghojjang/backend:latest
    build:
      context: ./BE/losszero
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=secret
    # 11/4 . 10:23 김구태 추가
    depends_on:
      - mqtt

  frontend:
    image: leechanghojjang/frontend:latest
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped