version: '3'
services:
  backend:
    image: leechanghojjang/backend:latest
    build:
      context: ./BE/losszero
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=secret

  frontend:
    image: leechanghojjang/frontend:latest
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend