spring:
  datasource:
    url: jdbc:mysql://k11e202.p.ssafy.io:3306/losszero?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: losszero
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mqtt:
    broker-url: tcp://${spring.mqtt.hostname}:${spring.mqtt.port}
    automatic-reconnect: true
    clean-session: true
    connection-timeout: 10
    client-id: SpringBoot-MQTT-Client
    hostname: localhost
    port: 1883

logging:
  level:
    org.springframework: DEBUG