spring:
  jwt:
    secret: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0VXNlciIsImlhdCI6MTcyOTgzNjAzOCwiZXhwIjoxNzI5ODM5NjM4fQ.I7y8h4U2sDqEbhu_OYq-j10duR3wNLxTZhnhzpG2bPcLfDWiCNr9XsY-GPWrXobRoP1pSL6EKpbrPuwYrrRoEw  # JWT Secret Key
    expiration: 3600000  # 1시간 (ms 단위)