spring:
  datasource:
    url: jdbc:mysql://k11e202.p.ssafy.io:3306/losszero?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: losszero
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  ssl:
    key-store: keystore.p12
    key-store-password: losszeroe202
    keyStoreType: PKCS12
    keyAlias: myserver
  
  profiles:
    active: secret  # secret profile을 활성화

logging:
  level:
    org.springframework: DEBUG